openapi: 3.0.1
info:
  title: Price API
  description: API for querying prices based on date, product, and brand.
  version: "1.0"
paths:
  /price:
    get:
      summary: Get the applicable price
      description: Retrieves the applicable price for a product on a specific date and for a given brand.
      parameters:
        - name: applicationDate
          in: query
          required: true
          description: Application date and time in the format 'yyyy-MM-dd-HH.mm.ss'
          schema:
            type: string
        - name: productId
          in: query
          required: true
          description: Product identifier
          schema:
            type: integer
        - name: brandId
          in: query
          required: true
          description: Brand identifier
          schema:
            type: integer
      responses:
        "200":
          description: Price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceGet200Response'
        "404":
          description: Price not found
components:
  schemas:
    PriceGet200Response:
      type: object
      properties:
        brandId:
          type: integer
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        priceList:
          type: integer
        productId:
          type: integer
        priority:
          type: integer
        price:
          type: number
          format: double
        currency:
          type: string
