name: Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up KinD (Kubernetes in Docker)
      - name: Set up KinD (Kubernetes in Docker)
        uses: helm/kind-action@v1

      # Install ArgoCD
      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd

      # Set up ArgoCD CLI
      - name: Set up ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      # Get ArgoCD admin password
      - name: Get ArgoCD admin password
        run: |
          ARGO_PWD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          echo "::add-mask::$ARGO_PWD"
          echo "ARGOCD_PASSWORD=$ARGO_PWD" >> $GITHUB_ENV

      # Login to ArgoCD
      - name: Login to ArgoCD
        run: |
          kubectl port-forward svc/argocd-server -n argocd 8080:80 &
          sleep 10
          argocd login localhost:8080 --username admin --password "${{ env.ARGOCD_PASSWORD }}" --insecure

      # Deploy the application
      - name: Deploy application
        run: |
          argocd app sync BCNC
          argocd app wait BCNC --health
